#研究点数系统
ResearchPoints:
  enable: true
  #获取方式,格式为 <Action-动作>;<Points-得到的点数>;[Conditions-附加条件]
  #支持的动作如下
  #| get_exp——获取到经验时增长研究点数,<Points>表示为一点经验可以获得多少研究点数
  #| kill_mob——杀死生物时增长研究点数,注: 此类型动作可设置killed_mob来限定杀死的生物类型,
  #            并且此类型的动作没有附加条件时默认击杀所有生物都增长
  getWays:
    - get_exp;0.015
    - kill_mob;0.06;killed_mob = zombie

Database:
  #数据储存类型——只有SQLite
  #纯纯因为我懒
  StorageType: SQLite